Cheetah Software: VectorNavOrientationEstimator< T > Class Template Reference
VectorNavOrientationEstimator< T > Class Template Reference
#include <OrientationEstimator.h>
Public Member Functions
virtual void run ()
virtual void setup ()
Public Member Functions inherited from GenericEstimator< T >
void setData (StateEstimatorData< T > data)
virtual ~GenericEstimator ()=default
Protected Attributes
bool _b_first_visit = true
Quat< T > _ori_ini_inv
Additional Inherited Members
Public Attributes inherited from GenericEstimator< T >
StateEstimatorData< T > _stateEstimatorData
Detailed Description
template<typename T>
class VectorNavOrientationEstimator< T >
Estimator for the VectorNav IMU. The VectorNav provides an orientation already and we just return that.
Definition at line 32 of file OrientationEstimator.h.
Member Function Documentation
template<typename T > void VectorNavOrientationEstimator< T >::run () virtual
Get quaternion, rotation matrix, angular velocity (body and world), rpy, acceleration (world, body) from vector nav IMU
Implements GenericEstimator< T >.
Definition at line 44 of file OrientationEstimator.cpp.
References ori::quaternionToRotationMatrix(), ori::quatProduct(), ori::quatToRPY(), and ori::rpyToQuat().
{
   this->_stateEstimatorData.result->orientation[0] =
       this->_stateEstimatorData.vectorNavData->quat[3];
   this->_stateEstimatorData.result->orientation[1] =
       this->_stateEstimatorData.vectorNavData->quat[0];
   this->_stateEstimatorData.result->orientation[2] =
       this->_stateEstimatorData.vectorNavData->quat[1];
   this->_stateEstimatorData.result->orientation[3] =
       this->_stateEstimatorData.vectorNavData->quat[2];
   if(_b_first_visit){
     Vec3<T> rpy_ini = ori::quatToRPY(this->_stateEstimatorData.result->orientation);
     rpy_ini[0] = 0;
     rpy_ini[1] = 0;
     _ori_ini_inv = rpyToQuat(-rpy_ini);
     _b_first_visit = false;
   }
   this->_stateEstimatorData.result->orientation =
     ori::quatProduct(_ori_ini_inv, this->_stateEstimatorData.result->orientation);
   this->_stateEstimatorData.result->rpy =
       ori::quatToRPY(this->_stateEstimatorData.result->orientation);
   this->_stateEstimatorData.result->rBody = ori::quaternionToRotationMatrix(
       this->_stateEstimatorData.result->orientation);
   this->_stateEstimatorData.result->omegaBody =
       this->_stateEstimatorData.vectorNavData->gyro.template cast<T>();
   this->_stateEstimatorData.result->omegaWorld =
       this->_stateEstimatorData.result->rBody.transpose() *
       this->_stateEstimatorData.result->omegaBody;
   this->_stateEstimatorData.result->aBody =
       this->_stateEstimatorData.vectorNavData->accelerometer.template cast<T>();
   this->_stateEstimatorData.result->aWorld =
       this->_stateEstimatorData.result->rBody.transpose() *
       this->_stateEstimatorData.result->aBody;
 }
template<typename T > virtual void VectorNavOrientationEstimator< T >::setup () inline virtual
Implements GenericEstimator< T >.
Definition at line 35 of file OrientationEstimator.h.
 {}
Member Data Documentation
template<typename T > bool VectorNavOrientationEstimator< T >::_b_first_visit = true protected
Definition at line 38 of file OrientationEstimator.h.
template<typename T > Quat<T> VectorNavOrientationEstimator< T >::_ori_ini_inv protected
Definition at line 39 of file OrientationEstimator.h.
The documentation for this class was generated from the following files:
OrientationEstimator.h
OrientationEstimator.cpp