/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class cheetah_visualization_lcmt implements lcm.lcm.LCMEncodable
{
    public float q[];
    public float x[];
    public float quat[];
    public float rgba[];
 
    public cheetah_visualization_lcmt()
    {
        q = new float[12];
        x = new float[3];
        quat = new float[4];
        rgba = new float[4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xe9e9209bb36f494fL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.cheetah_visualization_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.cheetah_visualization_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.q[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.x[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.quat[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.rgba[a]); 
        }
 
    }
 
    public cheetah_visualization_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public cheetah_visualization_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.cheetah_visualization_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.cheetah_visualization_lcmt o = new lcmtypes.cheetah_visualization_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.q = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.q[a] = ins.readFloat();
        }
 
        this.x = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.x[a] = ins.readFloat();
        }
 
        this.quat = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.quat[a] = ins.readFloat();
        }
 
        this.rgba = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.rgba[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.cheetah_visualization_lcmt copy()
    {
        lcmtypes.cheetah_visualization_lcmt outobj = new lcmtypes.cheetah_visualization_lcmt();
        outobj.q = new float[(int) 12];
        System.arraycopy(this.q, 0, outobj.q, 0, 12); 
        outobj.x = new float[(int) 3];
        System.arraycopy(this.x, 0, outobj.x, 0, 3); 
        outobj.quat = new float[(int) 4];
        System.arraycopy(this.quat, 0, outobj.quat, 0, 4); 
        outobj.rgba = new float[(int) 4];
        System.arraycopy(this.rgba, 0, outobj.rgba, 0, 4); 
        return outobj;
    }
 
}

