/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class control_parameter_respones_lcmt implements lcm.lcm.LCMEncodable
{
    public byte name[];
    public long requestNumber;
    public byte value[];
    public byte parameterKind;
    public byte requestKind;
 
    public control_parameter_respones_lcmt()
    {
        name = new byte[64];
        value = new byte[64];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xe827e9f6525296b9L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.control_parameter_respones_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.control_parameter_respones_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.write(this.name, 0, 64);
 
        outs.writeLong(this.requestNumber); 
 
        outs.write(this.value, 0, 64);
 
        outs.writeByte(this.parameterKind); 
 
        outs.writeByte(this.requestKind); 
 
    }
 
    public control_parameter_respones_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public control_parameter_respones_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.control_parameter_respones_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.control_parameter_respones_lcmt o = new lcmtypes.control_parameter_respones_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.name = new byte[(int) 64];
        ins.readFully(this.name, 0, 64); 
        this.requestNumber = ins.readLong();
 
        this.value = new byte[(int) 64];
        ins.readFully(this.value, 0, 64); 
        this.parameterKind = ins.readByte();
 
        this.requestKind = ins.readByte();
 
    }
 
    public lcmtypes.control_parameter_respones_lcmt copy()
    {
        lcmtypes.control_parameter_respones_lcmt outobj = new lcmtypes.control_parameter_respones_lcmt();
        outobj.name = new byte[(int) 64];
        System.arraycopy(this.name, 0, outobj.name, 0, 64); 
        outobj.requestNumber = this.requestNumber;
 
        outobj.value = new byte[(int) 64];
        System.arraycopy(this.value, 0, outobj.value, 0, 64); 
        outobj.parameterKind = this.parameterKind;
 
        outobj.requestKind = this.requestKind;
 
        return outobj;
    }
 
}

