/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class rpc_data_t implements lcm.lcm.LCMEncodable
{
    public double cpu_opt_time_microseconds;
    public double t_sent;
    public double time_start;
    public double dt_pred[];
    public double x_opt[][];
    public double u_opt[][];
    public double p_opt[][];
 
    public rpc_data_t()
    {
        dt_pred = new double[8];
        x_opt = new double[8][12];
        u_opt = new double[8][24];
        p_opt = new double[3][4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xf933cc03f4843206L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.rpc_data_t.class))
            return 0L;
 
        classes.add(lcmtypes.rpc_data_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeDouble(this.cpu_opt_time_microseconds); 
 
        outs.writeDouble(this.t_sent); 
 
        outs.writeDouble(this.time_start); 
 
        for (int a = 0; a < 8; a++) {
            outs.writeDouble(this.dt_pred[a]); 
        }
 
        for (int a = 0; a < 8; a++) {
            for (int b = 0; b < 12; b++) {
                outs.writeDouble(this.x_opt[a][b]); 
            }
        }
 
        for (int a = 0; a < 8; a++) {
            for (int b = 0; b < 24; b++) {
                outs.writeDouble(this.u_opt[a][b]); 
            }
        }
 
        for (int a = 0; a < 3; a++) {
            for (int b = 0; b < 4; b++) {
                outs.writeDouble(this.p_opt[a][b]); 
            }
        }
 
    }
 
    public rpc_data_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public rpc_data_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.rpc_data_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.rpc_data_t o = new lcmtypes.rpc_data_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.cpu_opt_time_microseconds = ins.readDouble();
 
        this.t_sent = ins.readDouble();
 
        this.time_start = ins.readDouble();
 
        this.dt_pred = new double[(int) 8];
        for (int a = 0; a < 8; a++) {
            this.dt_pred[a] = ins.readDouble();
        }
 
        this.x_opt = new double[(int) 8][(int) 12];
        for (int a = 0; a < 8; a++) {
            for (int b = 0; b < 12; b++) {
                this.x_opt[a][b] = ins.readDouble();
            }
        }
 
        this.u_opt = new double[(int) 8][(int) 24];
        for (int a = 0; a < 8; a++) {
            for (int b = 0; b < 24; b++) {
                this.u_opt[a][b] = ins.readDouble();
            }
        }
 
        this.p_opt = new double[(int) 3][(int) 4];
        for (int a = 0; a < 3; a++) {
            for (int b = 0; b < 4; b++) {
                this.p_opt[a][b] = ins.readDouble();
            }
        }
 
    }
 
    public lcmtypes.rpc_data_t copy()
    {
        lcmtypes.rpc_data_t outobj = new lcmtypes.rpc_data_t();
        outobj.cpu_opt_time_microseconds = this.cpu_opt_time_microseconds;
 
        outobj.t_sent = this.t_sent;
 
        outobj.time_start = this.time_start;
 
        outobj.dt_pred = new double[(int) 8];
        System.arraycopy(this.dt_pred, 0, outobj.dt_pred, 0, 8); 
        outobj.x_opt = new double[(int) 8][(int) 12];
        for (int a = 0; a < 8; a++) {
            System.arraycopy(this.x_opt[a], 0, outobj.x_opt[a], 0, 12);        }
 
        outobj.u_opt = new double[(int) 8][(int) 24];
        for (int a = 0; a < 8; a++) {
            System.arraycopy(this.u_opt[a], 0, outobj.u_opt[a], 0, 24);        }
 
        outobj.p_opt = new double[(int) 3][(int) 4];
        for (int a = 0; a < 3; a++) {
            System.arraycopy(this.p_opt[a], 0, outobj.p_opt[a], 0, 4);        }
 
        return outobj;
    }
 
}

