/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class velocity_visual_t implements lcm.lcm.LCMEncodable
{
    public double vel_cmd[];
    public double base_position[];
 
    public velocity_visual_t()
    {
        vel_cmd = new double[3];
        base_position = new double[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x939f71540029b78bL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.velocity_visual_t.class))
            return 0L;
 
        classes.add(lcmtypes.velocity_visual_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.vel_cmd[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.base_position[a]); 
        }
 
    }
 
    public velocity_visual_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public velocity_visual_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.velocity_visual_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.velocity_visual_t o = new lcmtypes.velocity_visual_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.vel_cmd = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.vel_cmd[a] = ins.readDouble();
        }
 
        this.base_position = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.base_position[a] = ins.readDouble();
        }
 
    }
 
    public lcmtypes.velocity_visual_t copy()
    {
        lcmtypes.velocity_visual_t outobj = new lcmtypes.velocity_visual_t();
        outobj.vel_cmd = new double[(int) 3];
        System.arraycopy(this.vel_cmd, 0, outobj.vel_cmd, 0, 3); 
        outobj.base_position = new double[(int) 3];
        System.arraycopy(this.base_position, 0, outobj.base_position, 0, 3); 
        return outobj;
    }
 
}

