Cheetah Software: RobotController Class Reference
RobotController Class Reference abstract
#include <RobotController.h>
Public Member Functions
RobotController ()
virtual ~RobotController ()
virtual void initializeController ()=0
virtual void runController ()=0
virtual void updateVisualization ()=0
virtual ControlParameters * getUserControlParameters ()=0
virtual void Estop ()
Protected Attributes
Quadruped< float > * _quadruped = nullptr
FloatingBaseModel< float > * _model = nullptr
LegController< float > * _legController = nullptr
StateEstimatorContainer< float > * _stateEstimator = nullptr
StateEstimate< float > * _stateEstimate = nullptr
GamepadCommand * _driverCommand = nullptr
RobotControlParameters * _controlParameters = nullptr
DesiredStateCommand< float > * _desiredStateCommand = nullptr
VisualizationData * _visualizationData = nullptr
RobotType _robotType
Friends
class RobotRunner
Detailed Description
Parent class of user robot controllers
Definition at line 20 of file RobotController.h.
Constructor & Destructor Documentation
RobotController::RobotController () inline
Definition at line 23 of file RobotController.h.
 {}
virtual RobotController::~RobotController () inline virtual
Definition at line 24 of file RobotController.h.
References getUserControlParameters(), initializeController(), runController(), and updateVisualization().
 {}
Member Function Documentation
virtual void RobotController::Estop () inline virtual
Definition at line 33 of file RobotController.h.
 {}
virtual ControlParameters* RobotController::getUserControlParameters () pure virtual
virtual void RobotController::initializeController () pure virtual
virtual void RobotController::runController () pure virtual
Called one time every control loop
virtual void RobotController::updateVisualization () pure virtual
Friends And Related Function Documentation
friend class RobotRunner friend
Definition at line 21 of file RobotController.h.
Member Data Documentation
RobotControlParameters* RobotController::_controlParameters = nullptr protected
Definition at line 42 of file RobotController.h.
DesiredStateCommand<float>* RobotController::_desiredStateCommand = nullptr protected
Definition at line 43 of file RobotController.h.
GamepadCommand* RobotController::_driverCommand = nullptr protected
Definition at line 41 of file RobotController.h.
LegController<float>* RobotController::_legController = nullptr protected
Definition at line 38 of file RobotController.h.
FloatingBaseModel<float>* RobotController::_model = nullptr protected
Definition at line 37 of file RobotController.h.
Quadruped<float>* RobotController::_quadruped = nullptr protected
Definition at line 36 of file RobotController.h.
RobotType RobotController::_robotType protected
Definition at line 46 of file RobotController.h.
StateEstimate<float>* RobotController::_stateEstimate = nullptr protected
Definition at line 40 of file RobotController.h.
StateEstimatorContainer<float>* RobotController::_stateEstimator = nullptr protected
Definition at line 39 of file RobotController.h.
VisualizationData* RobotController::_visualizationData = nullptr protected
Definition at line 45 of file RobotController.h.
The documentation for this class was generated from the following file:
RobotController.h