Cheetah Software: SparseCMPC Class Reference
SparseCMPC Class Reference
#include <SparseCMPC.h>
Public Member Functions
SparseCMPC ()
void run ()
template<typename T >
void setRobotParameters (Mat3< T > &inertia, T mass, T maxForce)
void setFriction (double mu)
template<typename T >
void setWeights (Vec12< T > &weights, T alpha)
template<typename T >
void setX0 (Vec3< T > p, Vec3< T > v, Vec4< T > q, Vec3< T > w)
void setContactTrajectory (ContactState *contacts, std::size_t length)
void setStateTrajectory (vectorAligned< Vec12< double >> &traj)
template<typename T >
void setDtTrajectory (std::vector< T > &traj)
template<typename T >
void setFeet (Vec12< T > &feet)
Vec12< float > getResult ()
Private Member Functions
void buildX0 ()
void buildCT ()
void buildDT ()
void c2d (u32 trajIdx, u32 bBlockStartIdx, u32 block_count)
u32 getStateIndex (u32 trajIdx)
u32 getControlIndex (u32 bBlockIdx)
u32 addConstraint (u32 size)
void addConstraintTriple (double value, u32 row, u32 col)
void addX0Constraint ()
void addDynamicsConstraints ()
void addForceConstraints ()
void addFrictionConstraints ()
void addQuadraticStateCost ()
void addLinearStateCost ()
void addQuadraticControlCost ()
void runSolver ()
void runSolverOSQP ()
Private Attributes
Mat3< double > _Ibody
Vec12< double > _weights
double _mass
double _maxForce
double _mu
double _alpha
Vec3< double > _p0
Vec3< double > _v0
Vec3< double > _w0
Vec3< double > _rpy0
Vec4< double > _q0
Vec12< double > _x0
Vec12< double > _pFeet
Vec12< double > _g
std::vector< ContactState > _contactTrajectory
vectorAligned< Vec12< double > > _stateTrajectory
std::vector< double > _dtTrajectory
vectorAligned< Mat12< double > > _aMat
std::vector< BblockID > _bBlockIds
vectorAligned< Eigen::Matrix< double, 12, 3 > > _bBlocks
std::vector< u32 > _contactCounts
std::vector< u32 > _runningContactCounts
std::vector< SparseTriple< double > > _constraintTriples
std::vector< SparseTriple< double > > _costTriples
std::vector< double > _lb
std::vector< double > _ub
std::vector< double > _linearCost
Eigen::Matrix< float, Eigen::Dynamic, 1 > _result
u32 _trajectoryLength
u32 _bBlockCount
u32 _constraintCount
Detailed Description
Definition at line 13 of file SparseCMPC.h.
Constructor & Destructor Documentation
SparseCMPC::SparseCMPC ()
Definition at line 24 of file SparseCMPC.cpp.
{
 }
Member Function Documentation
u32 SparseCMPC::addConstraint (u32 size) private
Definition at line 167 of file SparseCMPC.cpp.
References _constraintCount.
{
   u32 rv = _constraintCount;
   _constraintCount += size;
   return rv;
 }
void SparseCMPC::addConstraintTriple (double value, u32 row, u32 col) private
Definition at line 173 of file SparseCMPC.cpp.
References _bBlockCount, _constraintCount, _constraintTriples, and _trajectoryLength.
{
   assert(col < 12 * _trajectoryLength + 3 * _bBlockCount);
   assert(row < _constraintCount);
   if(value != 0) {
     _constraintTriples.push_back({value, row, col});
   }
 }
void SparseCMPC::addDynamicsConstraints () private
Definition at line 221 of file SparseCMPC.cpp.
References _aMat, _bBlocks, _constraintTriples, _contactCounts, _dtTrajectory, _g, _lb, _runningContactCounts, _trajectoryLength, _ub, addConstraint(), addConstraintTriple(), getControlIndex(), and getStateIndex().
{
   // x[n] = A[n] * x[n-1] + B[n] * u[n] + g * dt[n]
   for(u32 i = 1; i < _trajectoryLength; i++) {
     u32 next_state_idx = getStateIndex(i);
     u32 prev_state_idx = getStateIndex(i - 1);
     u32 constraint_idx = addConstraint(12);
     // get I * x[n]
     for(u32 j = 0; j < 12; j++) {
       _constraintTriples.push_back({1, constraint_idx + j, next_state_idx + j});
     }
     // get -A[n] * x[n-1]
     for(u32 r = 0; r < 12; r++) {
       for(u32 c = 0; c < 12; c++) {
         addConstraintTriple(-_aMat[i](r,c), constraint_idx + r, prev_state_idx + c);
       }
     }
     // get -B[n] * u[n]
     u32 contact_count = _contactCounts[i];
     u32 bb_idx = _runningContactCounts[i];
     for(u32 contact = 0; contact < contact_count; contact++) {
       for(u32 row = 0; row < 12; row++) {
         for(u32 col = 0; col < 3; col++) {
           addConstraintTriple(-_bBlocks[bb_idx + contact](row, col),
             constraint_idx + row,
             getControlIndex(bb_idx + contact) + col);
         }
       }
     }
     // rhs g*dt
     Vec12<double> rhs = _g * _dtTrajectory[i];
     for(u32 j = 0; j < 12; j++) {
       _ub.push_back(rhs[j]);
       _lb.push_back(rhs[j]);
     }
 //    u32 idx2 = addConstraint(1);
 //    addConstraintTriple(1., idx2, getStateIndex(i) + 5);
 //    _lb.push_back(0);
 //    _ub.push_back(0.3);
   }
 }
void SparseCMPC::addForceConstraints () private
Definition at line 269 of file SparseCMPC.cpp.
References _bBlockCount, _lb, _maxForce, _ub, addConstraint(), addConstraintTriple(), and getControlIndex().
{
   // constrain all Z forces:
   for(u32 i = 0; i < _bBlockCount; i++) {
     _ub.push_back(_maxForce);
     _lb.push_back(0);
     addConstraintTriple(1, // directly get force
       addConstraint(1),    // new constraint
       getControlIndex(i) + 2 // ith contact's z force
       );
   }
 }
void SparseCMPC::addFrictionConstraints () private
Definition at line 281 of file SparseCMPC.cpp.
References _bBlockCount, _lb, _mu, _ub, addConstraint(), addConstraintTriple(), and getControlIndex().
{
   double muInv = 1. / _mu;
   for(u32 i = 0; i < _bBlockCount; i++) {
     // four friction constraints
     u32 constraint_idx = addConstraint(4);
     u32 control_idx    = getControlIndex(i);
     for(u32 c = 0; c < 4; c++) {
       _lb.push_back(0);
       _ub.push_back(1e15); // inf.
     }
     // x/mu + z > 0
     addConstraintTriple(muInv, constraint_idx + 0, control_idx + 0);
     addConstraintTriple(1, constraint_idx + 0, control_idx + 2);
     //-x/mu + z > 0
     addConstraintTriple(-muInv, constraint_idx + 1, control_idx + 0);
     addConstraintTriple(1, constraint_idx + 1, control_idx + 2);
     // y/mu + z > 0
     addConstraintTriple(muInv, constraint_idx + 2, control_idx + 1);
     addConstraintTriple(1, constraint_idx + 2, control_idx + 2);
     //-y/mu + z > 0
     addConstraintTriple(-muInv, constraint_idx + 3, control_idx + 1);
     addConstraintTriple(1, constraint_idx + 3, control_idx + 2);
   }
 }
void SparseCMPC::addLinearStateCost () private
Definition at line 329 of file SparseCMPC.cpp.
References _bBlockCount, _linearCost, _stateTrajectory, _trajectoryLength, _weights, and getStateIndex().
{
   _linearCost.resize(12 * _trajectoryLength + 3 * _bBlockCount);
   for(auto& v : _linearCost) v = 0;
   // -2 * w * x_des
   //printf("z des traj: ");
   for(u32 i = 0; i < _trajectoryLength; i++) {
     u32 idx = getStateIndex(i);
     for(u32 j = 0; j < 12; j++) {
       _linearCost.at(idx + j) = -1. * _stateTrajectory[i][j] * _weights[j];
     }
    // printf("%.3f ", _stateTrajectory[i][5]);
   }
   //printf("\n");
 }
void SparseCMPC::addQuadraticControlCost () private
Definition at line 320 of file SparseCMPC.cpp.
References _alpha, _bBlockCount, _costTriples, and getControlIndex().
{
   for(u32 i = 0; i < _bBlockCount; i++) {
     u32 idx = getControlIndex(i);
     for(u32 j = 0; j < 3; j++) {
       _costTriples.push_back({_alpha, idx + j, idx + j});
     }
   }
 }
void SparseCMPC::addQuadraticStateCost () private
Definition at line 310 of file SparseCMPC.cpp.
References _costTriples, _trajectoryLength, _weights, and getStateIndex().
{
   // xt Q x
   for(u32 i = 0; i < _trajectoryLength; i++) {
     u32 idx = getStateIndex(i);
     for(u32 j = 0; j < 12; j++) {
       _costTriples.push_back({_weights[j], idx + j, idx + j});
     }
   }
 }
void SparseCMPC::addX0Constraint () private
Definition at line 182 of file SparseCMPC.cpp.
References _aMat, _bBlocks, _constraintTriples, _contactCounts, _dtTrajectory, _g, _lb, _runningContactCounts, _ub, _x0, addConstraint(), addConstraintTriple(), getControlIndex(), and getStateIndex().
{
   // x[0] = A[0] * X0 + B[0] * u[0] + g*dt;
   // x[0] - (B[0] * u[0]) = A[0]*X0 + g*dt;
   // select x[0] with identity matrix
   u32 state_idx = getStateIndex(0);
   u32 constraint_idx = addConstraint(12);
   for(u32 i = 0; i < 12; i++) { // diagonal of the identity
     _constraintTriples.push_back({1,constraint_idx + i, state_idx + i});
   }
   if(_runningContactCounts[0]) throw std::runtime_error("contact count error!");
   u32 ctrl_cnt = _contactCounts[0];
   for(u32 i = 0; i < ctrl_cnt; i++) { // Bblocks within this b (contact feet)
     // select -B[0]*u[0]
     u32 bbIdx = _runningContactCounts[0] + i;
     for(u32 ax = 0; ax < 3; ax++) { // columns within the b block (forces axes)
       for(u32 row = 0; row < 12; row++) { // rows within the b block
         addConstraintTriple(-_bBlocks[bbIdx](row, ax), constraint_idx + row, getControlIndex(bbIdx) + ax);
       }
     }
   }
   // compute right hand side A[0]*X0 + g*dt.
   Vec12<double> rhs = _aMat[0] * _x0 + _g * _dtTrajectory[0];
 //  printf("x0: \n");
 //  std::cout << _x0.transpose() << "\n";
   // add to problem.
   for(u32 i = 0; i < 12; i++) {
     _ub.push_back(rhs[i]);
     _lb.push_back(rhs[i]);
   }
 }
void SparseCMPC::buildCT () private
Build continuous time matrices. uses trajectory yaw for yaw integration, not trajectory omega.
Definition at line 88 of file SparseCMPC.cpp.
References _aMat, _bBlockCount, _bBlockIds, _bBlocks, _contactTrajectory, _Ibody, _mass, _pFeet, _rpy0, _trajectoryLength, ori::coordinateRotation(), ori::crossMatrix(), and ori::Z.
{
 //  for(u32 foot = 0; foot < 4; foot++) {
 //    Vec3<double> pFoot = _pFeet.block(foot*3,0,3,1);
 //    printf("FOOT %d: %6.3f, %6.3f %6.3f\n", foot, pFoot[0], pFoot[1], pFoot[2]);
 //  }
   // one 12x12 A matrix per timestep
   _aMat.clear();
   _aMat.resize(_trajectoryLength);
   // B "blocks" are for a single foot for a single iteration (so 12x3)
   _bBlockIds.clear();
   _bBlocks.clear();
   // loop over trajectory
   for(u32 i = 0; i < _trajectoryLength; i++) {
     // rotation from world into yaw frame
     //Mat3<double> Ryaw = ori::coordinateRotation(ori::CoordinateAxis::Z, _stateTrajectory[i][2]); // todo check
     Mat3<double> Ryaw = ori::coordinateRotation(ori::CoordinateAxis::Z, _rpy0[2]);
     // transform inertia to world and invert
     Mat3<double> Iworld = Ryaw.transpose() * _Ibody * Ryaw;
     Mat3<double> Iinv = Iworld.inverse();
     // build A matrix (continuous time)
     Mat12<double>& A = _aMat[i];
     A.setZero();
     A(3,9) = 1; // x position integration
     A(4,10) = 1; // y position integration
     A(5,11) = 1; // z position integration
     A.block(0,6,3,3) = Ryaw; // omega integration
     // build up to four B blocks for the four feet
     auto& contactState = _contactTrajectory[i];
     for(uint32_t foot = 0; foot < 4; foot++) {
       if(contactState.contact[foot]) { // if foot is touching ground, add it.
         _bBlocks.emplace_back();
         _bBlockIds.push_back({foot, i});
         auto& B = _bBlocks.back();
         Vec3<double> pFoot = _pFeet.block(foot*3,0,3,1);
         B.setZero();
         B.block(6,0,3,3) = Iinv * ori::crossMatrix(pFoot);    // r x f torque
         B.block(9,0,3,3) = Mat3<double>::Identity() / _mass;  // f = ma
       }
     }
   }
   _bBlockCount = _bBlockIds.size();
 }
void SparseCMPC::buildDT () private
Build discrete time matrices
Definition at line 140 of file SparseCMPC.cpp.
References _contactCounts, _contactTrajectory, _runningContactCounts, _trajectoryLength, and c2d().
{
   u32 runningContactCount = 0;
   for(u32 i = 0; i < _trajectoryLength; i++) {
     u32 contactCount = 0;
     for(auto contact : _contactTrajectory[i].contact) {
       if(contact) contactCount++;
     }
     _contactCounts.push_back(contactCount);
     _runningContactCounts.push_back(runningContactCount);
     c2d(i, runningContactCount, contactCount);
     runningContactCount += contactCount;
   }
 }
void SparseCMPC::buildX0 () private
Configure initial state of robot _rpy0, _x0
Definition at line 79 of file SparseCMPC.cpp.
References _p0, _q0, _rpy0, _v0, _w0, _x0, and ori::quatToRPY().
{
   _rpy0 = ori::quatToRPY(_q0);
   _x0 << _rpy0, _p0, _w0, _v0;
 }
void SparseCMPC::c2d (u32 trajIdx, u32 bBlockStartIdx, u32 block_count) private
Definition at line 6 of file SparseCMPC_Math.cpp.
References _aMat, _bBlockIds, _bBlocks, and _dtTrajectory.
{
   Eigen::Matrix<double, 24, 24> AB, expmm;
   AB.setZero();
   AB.block(0,0,12,12) = _aMat[trajIdx];
   for(u32 i = bBlockStartIdx; i < bBlockStartIdx + block_count; i++) {
     BblockID id = _bBlockIds[i];
     if(id.timestep != trajIdx) throw std::runtime_error("c2d timestep error");
     AB.block(0,12 + 3 * id.foot, 12, 3) = _bBlocks[i];
   }
   AB *= _dtTrajectory[trajIdx];
   expmm = AB.exp();
   _aMat[trajIdx] = expmm.block(0,0,12,12);
   for(u32 i = bBlockStartIdx; i < bBlockStartIdx + block_count; i++) {
     //BblockID id = _bBlockIds[i];
     //_bBlocks[i] = expmm.block(0,12 + 3 * id.foot, 12, 3);
     _bBlocks[i] *= _dtTrajectory[trajIdx];
   }
 }
u32 SparseCMPC::getControlIndex (u32 bBlockIdx) private
Definition at line 162 of file SparseCMPC.cpp.
References _bBlockCount, and _trajectoryLength.
{
   assert(bBlockIdx < _bBlockCount);
   return (_trajectoryLength * 12) + (bBlockIdx * 3);
 }
Vec12< float > SparseCMPC::getResult ()
Definition at line 379 of file SparseCMPC.cpp.
References _bBlockIds, _result, and getControlIndex().
{
 //  for(u32 i = 0; i < 12; i++) {
 //    printf("%s: ", names[i]);
 //    for(u32 j = 0; j < _trajectoryLength; j++) {
 //      printf("%6.3f  ", _result[getStateIndex(j) + i]);
 //    }
 //    printf("\n");
 //  }
 //
 //  printf("zf traj: ");
 //  for(u32 i = 0; i < _bBlockCount; i++) {
 //    printf("[%2d %3.3f]  ", _bBlockIds[i].timestep, _result[getControlIndex(i) + 2]);
 //  }
 //  printf("\n");
   Vec12<float> result;
   result.setZero();
   for(u32 i = 0; i < _bBlockIds.size(); i++) {
     auto& id = _bBlockIds[i];
     if(id.timestep == 0) {
       //printf("result for foot %d %.3f %.3f %.3f\n", id.foot, _result[getControlIndex(i) + 0], _result[getControlIndex(i) + 1], _result[getControlIndex(i) + 2]);
       for(u32 j = 0; j < 3; j++) {
         result[id.foot*3 + j] = _result[getControlIndex(i) + j];
       }
     }
   }
   return result;
 }
u32 SparseCMPC::getStateIndex (u32 trajIdx) private
Definition at line 157 of file SparseCMPC.cpp.
References _trajectoryLength.
{
   assert(trajIdx < _trajectoryLength);
   return trajIdx * 12;
 }
void SparseCMPC::run ()
Definition at line 31 of file SparseCMPC.cpp.
References _bBlockCount, _constraintCount, _constraintTriples, _contactCounts, _contactTrajectory, _costTriples, _dtTrajectory, _g, _lb, _runningContactCounts, _stateTrajectory, _trajectoryLength, _ub, addDynamicsConstraints(), addForceConstraints(), addFrictionConstraints(), addLinearStateCost(), addQuadraticControlCost(), addQuadraticStateCost(), addX0Constraint(), buildCT(), buildDT(), buildX0(), runSolverOSQP(), and Timer::start().
                      {
   Timer timer;
   // check trajectory length
   if((_stateTrajectory.size() != _contactTrajectory.size()) || (_contactTrajectory.size() != _dtTrajectory.size())) {
     throw std::runtime_error("SparseCMPC trajectory length error!");
   }
   // reset
   _g.setZero();
   _g[11] = -9.81;
   _constraintCount = 0;
   _trajectoryLength = _stateTrajectory.size();
   _constraintTriples.clear();
   _costTriples.clear();
   _ub.clear();
   _lb.clear();
   _contactCounts.clear();
   _runningContactCounts.clear();
   _bBlockCount = 0;
   // build initial state and data
   buildX0();
   buildCT();
   buildDT();
   //printf("t1: %.3f\n", timer.getMs());
   timer.start();
   // build optimization problem
   addX0Constraint();
   addDynamicsConstraints();
   addForceConstraints();
   addFrictionConstraints();
   addQuadraticStateCost();
   addLinearStateCost();
   addQuadraticControlCost();
   //printf("t2: %.3f\n", timer.getMs());
   // Solve!
   //runSolver();
   runSolverOSQP();
 }
void SparseCMPC::runSolver () private
Definition at line 345 of file SparseCMPC.cpp.
References _bBlockCount, _constraintCount, _constraintTriples, _costTriples, _lb, _linearCost, _result, _trajectoryLength, and _ub.
{
   u32 varCount = 12 * _trajectoryLength + 3 * _bBlockCount;
   //printf("[SparseCMPC] Run %d, %d\n", varCount, _constraintCount);
   assert(_constraintCount == _ub.size());
   assert(_constraintCount == _lb.size());
   assert(varCount == _linearCost.size());
   QpProblem<double> solver(varCount, _constraintCount, false);
   solver.A_triples = std::move(_constraintTriples);
   solver.P_triples = std::move(_costTriples);
   solver.u = Vector<double>(_ub.size());
   solver.l = Vector<double>(_ub.size());
   for(u32 i = 0; i < _constraintCount; i++) {
     solver.u[i] = _ub[i];
     solver.l[i] = _lb[i];
   }
   solver.q = Vector<double>(varCount);
   for(u32 i = 0; i < varCount; i++) {
     solver.q[i] = _linearCost[i];
   }
   solver.settings.alpha = 1.5;
   solver.settings.rho = 1e-3;
   solver.settings.terminate = 1e-6;
   solver.settings.sigma = 1e-6;
   solver.runFromTriples(-1, true);
   _result = solver.getSolution().cast<float>();
 }
void SparseCMPC::runSolverOSQP () private
Definition at line 57 of file OsqpTriples.cpp.
References OsqpCSC::colPtrs, compress(), OsqpCSC::freeAll(), OsqpCSC::nnz, OsqpCSC::rowIdx, Timer::start(), and OsqpCSC::values.
{
   Timer timer;
   u32 varCount = 12 * _trajectoryLength + 3 * _bBlockCount;
   //printf("[SparseCMPC] Run with OSQP %d, %d\n", varCount, _constraintCount);
   assert(_constraintCount == _ub.size());
   assert(_constraintCount == _lb.size());
   assert(varCount == _linearCost.size());
   // Quadratic term
   sortAndSumTriples(_costTriples);
   OsqpCSC quadraticCostMatrix = compress(_costTriples, varCount, varCount);
   sortAndSumTriples(_constraintTriples);
   OsqpCSC constraintMatrix = compress(_constraintTriples, _constraintCount, varCount);
   OSQPSettings* settings = (OSQPSettings*)malloc(sizeof(OSQPSettings));
   OSQPWorkspace* workspace;
   (void)workspace;
   OSQPData* data = (OSQPData*)malloc(sizeof(OSQPData));
   data->n = varCount;
   data->m = _constraintCount;
   data->P = csc_matrix(varCount, varCount, quadraticCostMatrix.nnz,
       quadraticCostMatrix.values, quadraticCostMatrix.rowIdx, quadraticCostMatrix.colPtrs);
   data->q = _linearCost.data();
   data->A = csc_matrix(_constraintCount, varCount, constraintMatrix.nnz,
       constraintMatrix.values, constraintMatrix.rowIdx, constraintMatrix.colPtrs);
   data->l = _lb.data();
   data->u = _ub.data();
   //printf("t3: %.3f\n", timer.getMs());
   timer.start();
 //# define EPS_ABS (1E-3)
 //# define EPS_REL (1E-3)
 //# define EPS_PRIM_INF (1E-4)
 //# define EPS_DUAL_INF (1E-4)
   osqp_set_default_settings(settings);
   settings->eps_abs = 1e-5;
   settings->eps_rel = 1e-5;
   //settings->max_iter = 300;
   //settings->alpha = 1.0; //todo try me
   workspace = osqp_setup(data, settings);
   //printf("t4: %.3f\n", timer.getMs());
   timer.start();
   osqp_solve(workspace);
   //printf("t5: %.3f\n", timer.getMs());
   _result = Eigen::Matrix<float, Eigen::Dynamic, 1>(varCount);
   for(u32 i = 0; i < varCount; i++) {
     _result[i] = workspace->solution->x[i];
   }
 //
 //
 //
 //  osqp_cleanup(workspace);
 //  QpProblem<double> solver(varCount, _constraintCount, false);
 //  solver.A_triples = std::move(_constraintTriples);
 //  solver.P_triples = std::move(_costTriples);
 //  solver.u = Vector<double>(_ub.size());
 //  solver.l = Vector<double>(_ub.size());
 //  for(u32 i = 0; i < _constraintCount; i++) {
 //    solver.u[i] = _ub[i];
 //    solver.l[i] = _lb[i];
 //  }
 //  solver.q = Vector<double>(varCount);
 //  for(u32 i = 0; i < varCount; i++) {
 //    solver.q[i] = _linearCost[i];
 //  }
 //
 //  solver.settings.alpha = 1.5;
 //  solver.settings.rho = 1e-3;
 //  solver.settings.terminate = 1e-6;
 //  solver.settings.sigma = 1e-6;
 //
 //
 //  solver.runFromTriples(-1, true);
 //  _result = solver.getSolution().cast<float>();
   quadraticCostMatrix.freeAll();
   constraintMatrix.freeAll();
 }
void SparseCMPC::setContactTrajectory (ContactState * contacts, std::size_t length) inline
Definition at line 45 of file SparseCMPC.h.
{
     _contactTrajectory.resize(length);
     for(std::size_t i = 0; i < length; i++) {
       _contactTrajectory[i] = contacts[i];
     }
   }
template<typename T > void SparseCMPC::setDtTrajectory (std::vector< T > & traj) inline
Definition at line 57 of file SparseCMPC.h.
{
     _dtTrajectory.clear();
     _dtTrajectory.reserve(traj.size());
     for(auto pt : traj)
       _dtTrajectory.push_back(pt);
   }
template<typename T > void SparseCMPC::setFeet (Vec12< T > & feet) inline
Definition at line 65 of file SparseCMPC.h.
{
     _pFeet = feet.template cast<double>();
   }
void SparseCMPC::setFriction (double mu) inline
Definition at line 27 of file SparseCMPC.h.
{
     _mu = mu;
   }
template<typename T > void SparseCMPC::setRobotParameters (Mat3< T > & inertia, T mass, T maxForce) inline
Definition at line 21 of file SparseCMPC.h.
{
     _Ibody = inertia.template cast<double>();
     _mass = mass;
     _maxForce = maxForce;
   }
void SparseCMPC::setStateTrajectory (vectorAligned< Vec12< double >> & traj) inline
Definition at line 52 of file SparseCMPC.h.
{
     _stateTrajectory = traj;
   }
template<typename T > void SparseCMPC::setWeights (Vec12< T > & weights, T alpha) inline
Definition at line 32 of file SparseCMPC.h.
{
     _weights = weights.template cast<double>();
     _alpha = alpha;
   }
template<typename T > void SparseCMPC::setX0 (Vec3< T > p, Vec3< T > v, Vec4< T > q, Vec3< T > w) inline
Definition at line 38 of file SparseCMPC.h.
{
     _p0 = p.template cast<double>();
     _v0 = v.template cast<double>();
     _q0 = q.template cast<double>();
     _w0 = w.template cast<double>();
   }
Member Data Documentation
double SparseCMPC::_alpha private
Definition at line 102 of file SparseCMPC.h.
vectorAligned<Mat12<double> > SparseCMPC::_aMat private
Definition at line 114 of file SparseCMPC.h.
u32 SparseCMPC::_bBlockCount private
Definition at line 127 of file SparseCMPC.h.
std::vector<BblockID> SparseCMPC::_bBlockIds private
Definition at line 115 of file SparseCMPC.h.
vectorAligned<Eigen::Matrix<double,12,3> > SparseCMPC::_bBlocks private
Definition at line 116 of file SparseCMPC.h.
u32 SparseCMPC::_constraintCount private
Definition at line 128 of file SparseCMPC.h.
std::vector<SparseTriple<double> > SparseCMPC::_constraintTriples private
Definition at line 120 of file SparseCMPC.h.
std::vector<u32> SparseCMPC::_contactCounts private
Definition at line 117 of file SparseCMPC.h.
std::vector<ContactState> SparseCMPC::_contactTrajectory private
Definition at line 109 of file SparseCMPC.h.
std::vector<SparseTriple<double> > SparseCMPC::_costTriples private
Definition at line 120 of file SparseCMPC.h.
std::vector<double> SparseCMPC::_dtTrajectory private
Definition at line 111 of file SparseCMPC.h.
Vec12<double> SparseCMPC::_g private
Definition at line 106 of file SparseCMPC.h.
Mat3<double> SparseCMPC::_Ibody private
Definition at line 100 of file SparseCMPC.h.
std::vector<double> SparseCMPC::_lb private
Definition at line 121 of file SparseCMPC.h.
std::vector<double> SparseCMPC::_linearCost private
Definition at line 121 of file SparseCMPC.h.
double SparseCMPC::_mass private
Definition at line 102 of file SparseCMPC.h.
double SparseCMPC::_maxForce private
Definition at line 102 of file SparseCMPC.h.
double SparseCMPC::_mu private
Definition at line 102 of file SparseCMPC.h.
Vec3<double> SparseCMPC::_p0 private
Definition at line 103 of file SparseCMPC.h.
Vec12<double> SparseCMPC::_pFeet private
Definition at line 106 of file SparseCMPC.h.
Vec4<double> SparseCMPC::_q0 private
Definition at line 104 of file SparseCMPC.h.
Eigen::Matrix<float, Eigen::Dynamic, 1> SparseCMPC::_result private
Definition at line 123 of file SparseCMPC.h.
Vec3<double> SparseCMPC::_rpy0 private
Definition at line 103 of file SparseCMPC.h.
std::vector<u32> SparseCMPC::_runningContactCounts private
Definition at line 118 of file SparseCMPC.h.
vectorAligned<Vec12<double> > SparseCMPC::_stateTrajectory private
Definition at line 110 of file SparseCMPC.h.
u32 SparseCMPC::_trajectoryLength private
Definition at line 126 of file SparseCMPC.h.
std::vector<double> SparseCMPC::_ub private
Definition at line 121 of file SparseCMPC.h.
Vec3<double> SparseCMPC::_v0 private
Definition at line 103 of file SparseCMPC.h.
Vec3<double> SparseCMPC::_w0 private
Definition at line 103 of file SparseCMPC.h.
Vec12<double> SparseCMPC::_weights private
Definition at line 101 of file SparseCMPC.h.
Vec12<double> SparseCMPC::_x0 private
Definition at line 105 of file SparseCMPC.h.
The documentation for this class was generated from the following files:
SparseCMPC.h
OsqpTriples.cpp
SparseCMPC.cpp
SparseCMPC_Math.cpp