Cheetah Software: Timer Class Reference
Timer Class Reference
#include <Timer.h>
Public Member Functions
Timer ()
void start ()
double getMs ()
int64_t getNs ()
double getSeconds ()
Public Attributes
struct timespec _startTime
Detailed Description
Timer for measuring time elapsed with clock_monotonic
Definition at line 15 of file Timer.h.
Constructor & Destructor Documentation
Timer::Timer () inline explicit
Construct and start timer
Definition at line 21 of file Timer.h.
References start().
 { start(); }
Member Function Documentation
double Timer::getMs () inline
Get milliseconds elapsed
Definition at line 31 of file Timer.h.
References getNs().
 { return (double)getNs() / 1.e6; }
int64_t Timer::getNs () inline
Get nanoseconds elapsed
Definition at line 36 of file Timer.h.
References _startTime.
                   {
     struct timespec now;
     clock_gettime(CLOCK_MONOTONIC, &now);
     return (int64_t)(now.tv_nsec - _startTime.tv_nsec) +
            1000000000 * (now.tv_sec - _startTime.tv_sec);
   }
double Timer::getSeconds () inline
Get seconds elapsed
Definition at line 46 of file Timer.h.
References getNs().
 { return (double)getNs() / 1.e9; }
void Timer::start () inline
Start the timer
Definition at line 26 of file Timer.h.
References _startTime.
 { clock_gettime(CLOCK_MONOTONIC, &_startTime); }
Member Data Documentation
struct timespec Timer::_startTime
Definition at line 48 of file Timer.h.
The documentation for this class was generated from the following file:
Timer.h