# Generated on Sun Aug  2 17:55:51 2020
__collection-name__: user-parameters


Swing_step_offset   : [0, 0, 0]
cmpc_fmax           : 234
cmpc_gait           : 9
cmpc_mu             : 0.4
foot_hight          : 0.1
foot_location_k     : 0.03
sit_down_height     : 0.098
sit_down_time       : 1
stand_up_height     : 0.4
stride_max          : 0.3

Kd_body             : [4, 4, 4]
Kd_foot             : [8, 8, 8]
Kd_joint            : [0.64, 3.2, 3.2]
Kd_ori              : [80, 80, 80]
Kp_body             : [40, 40, 40]
Kp_foot             : [400, 400, 400]
Kp_joint            : [9.6, 48, 48]
Kp_ori              : [800, 800, 800]
