# Generated on Mon Aug  5 18:20:08 2019
__collection-name__: user-parameters

stride_max        : 0.3    #一步最大距离
cmpc_mu           : 0.4    #设置摩擦锥
cmpc_fmax         : 234    #最大足底力
foot_hight        : 0.1    #抬腿高度
foot_location_k   : 0.03   #落脚点设置系数
sit_down_height   : 0.098  #蹲下后的高度
stand_up_height   : 0.4    #站起时的高度
sit_down_time     : 1.0    #蹲下所需时间

Kd_joint          : [16, 3.2, 3.2]
Kp_joint          : [48, 48, 48]

Kp_body           : [400, 400, 400]
Kd_body           : [40, 40, 40]

Kp_foot           : [4000, 4000, 4000]
Kd_foot           : [80, 80, 80]

Kp_ori            : [800, 800, 800]
Kd_ori            : [80, 80, 80]

cmpc_gait         : 9    #确定当前步态
use_wbc           : 1

# Swing leg parameters
Swing_Kp_cartesian : [2000, 2000, 600]
Swing_Kd_cartesian : [44, 44, 44]
Swing_Kp_joint     : [0, 0, 0]
Swing_Kd_joint     : [3.2, 3.2, 3.2]
Swing_step_offset  : [0,0.05,-0.003]
Swing_traj_height  : 0.07
Swing_use_tau_ff   : 0

# Two Leg Stance parameters
Q_pos             : [20, 20, 20000]
Q_vel             : [0, 0, 0]
Q_ori             : [1500, 1900, 900]
Q_ang             : [30, 40, 10]

R_control         : 1.1
R_prev            : 2.0

two_leg_orient    : [0.225, 9.1, 0.0]
stance_legs       : 4

# Desired state commands
des_p             : [0,0,0.26]
des_theta         : [0,0,0]
des_dp            : [0,0,0]
des_dtheta        : [0,0,0]
des_theta_max     : [0,0.4,0]
des_dp_max        : [1.0,0.5,0]
des_dtheta_max    : [0,0,3]

# Gait parameters
gait_type             : 4        #gait_override = 1时生效,不用
gait_period_time      : 0.5      #gait_override = 2时生效,不用
gait_switching_phase  : 0.5      #gait_override = 2时生效,不用
gait_override         : 4        #调试步态的模式,不用
gait_max_leg_angle    : 15
gait_max_stance_time  : 0.25
gait_min_stance_time  : 0.1
