# Generated on Wed Jul 15 14:47:05 2020
__collection-name__: robot-parameters

cheater_mode               : 0
control_mode               : 6
controller_dt              : 0.002
foot_height_sensor_noise   : 0.001
foot_process_noise_position: 0.002
foot_sensor_noise_position : 0.001
foot_sensor_noise_velocity : 0.1
imu_process_noise_position : 0.02
imu_process_noise_velocity : 0.02
kdBase                     : [20, 10, 10]
kdCOM                      : [10, 10, 10]
kpBase                     : [300, 200, 100]
kpCOM                      : [50, 50, 50]
myValue                    : 2222
stand_kd_cartesian         : [2.5, 2.5, 2.5]
stand_kp_cartesian         : [50, 50, 50]
testValue                  : 23
use_rc                     : 0
