Cheetah Software: ControlParameter Class Reference
ControlParameter Class Reference
#include <ControlParameters.h>
Public Member Functions
ControlParameter (const std::string &name, double &value, ControlParameterCollection &collection, const std::string &units="")
ControlParameter (const std::string &name, float &value, ControlParameterCollection &collection, const std::string &units="")
ControlParameter (const std::string &name, s64 &value, ControlParameterCollection &collection, const std::string &units="")
ControlParameter (const std::string &name, Vec3< float > &value, ControlParameterCollection &collection, const std::string &units="")
ControlParameter (const std::string &name, Vec3< double > &value, ControlParameterCollection &collection, const std::string &units="")
ControlParameter (const std::string &name, ControlParameterValueKind kind)
void truncateName ()
void initializeDouble (double d)
void initializeFloat (float f)
void initializeInteger (s64 i)
void initializeVec3f (const Vec3< float > &v)
void initializeVec3d (const Vec3< double > &v)
void set (ControlParameterValue value, ControlParameterValueKind kind)
ControlParameterValue get (ControlParameterValueKind kind)
std::string toString ()
bool setFromString (const std::string &value)
Public Attributes
bool _set = false
ControlParameterValuePtr _value
std::string _name
std::string _units
ControlParameterValueKind _kind
ControlParameterValue _staticValue
Detailed Description
A single control parameter. Note that this representation doesn't store the value, just a pointer to an existing variable.
Definition at line 133 of file ControlParameters.h.
Constructor & Destructor Documentation
ControlParameter::ControlParameter (const std::string & name, double & value, ControlParameterCollection & collection, const std::string & units = "") inline
Construct control parameter for a double
Parameters
name : name of parameter
value : reference to value
collection : collection to add to
units : name of units
Definition at line 143 of file ControlParameters.h.
References ControlParameterCollection::addParameter(), and DOUBLE.
{
     _name = name;
     truncateName();
     _units = units;
     _value.d = &value;
     _kind = ControlParameterValueKind::DOUBLE;
     collection.addParameter(this, name);
   }
ControlParameter::ControlParameter (const std::string & name, float & value, ControlParameterCollection & collection, const std::string & units = "") inline
Construct control parameter for a float
Parameters
name : name of parameter
value : reference to value
collection : collection to add to
units : name of units
Definition at line 161 of file ControlParameters.h.
References ControlParameterCollection::addParameter(), and FLOAT.
{
     _name = name;
     truncateName();
     _units = units;
     _value.f = &value;
     _kind = ControlParameterValueKind::FLOAT;
     collection.addParameter(this, name);
   }
ControlParameter::ControlParameter (const std::string & name, s64 & value, ControlParameterCollection & collection, const std::string & units = "") inline
Construct control parameter for an s64
Parameters
name : name of parameter
value : reference to value
collection : collection to add to
units : name of units
Definition at line 179 of file ControlParameters.h.
References ControlParameterCollection::addParameter(), and S64.
{
     _name = name;
     truncateName();
     _units = units;
     _value.i = &value;
     _kind = ControlParameterValueKind::S64;
     collection.addParameter(this, name);
   }
ControlParameter::ControlParameter (const std::string & name, Vec3< float > & value, ControlParameterCollection & collection, const std::string & units = "") inline
Construct control parameter for a list of 3 floats
Parameters
name : name of parameter
value : reference to value
collection : collection to add to
units : name of units
Definition at line 197 of file ControlParameters.h.
References ControlParameterCollection::addParameter(), and VEC3_FLOAT.
{
     _name = name;
     truncateName();
     _units = units;
     _value.vec3f = value.data();
     _kind = ControlParameterValueKind::VEC3_FLOAT;
     collection.addParameter(this, name);
   }
ControlParameter::ControlParameter (const std::string & name, Vec3< double > & value, ControlParameterCollection & collection, const std::string & units = "") inline
Construct control parameter for a list of 3 doubles
Parameters
name : name of parameter
value : reference to value
collection : collection to add to
units : name of units
Definition at line 215 of file ControlParameters.h.
References ControlParameterCollection::addParameter(), and VEC3_DOUBLE.
{
     _name = name;
     truncateName();
     _units = units;
     _value.vec3d = value.data();
     _kind = ControlParameterValueKind::VEC3_DOUBLE;
     collection.addParameter(this, name);
   }
ControlParameter::ControlParameter (const std::string & name, ControlParameterValueKind kind) inline
Construct control parameter for a given type without adding it to a collection
Parameters
name : name of parameter
kind : type of data to be stored
Definition at line 232 of file ControlParameters.h.
{
     _name = name;
     truncateName();
     _kind = kind;
     _value.vec3d = (double*)&_staticValue;
   }
Member Function Documentation
ControlParameterValue ControlParameter::get (ControlParameterValueKind kind) inline
Get the value of a control parameter. Does type checking - you must provide the correct type.
Parameters
kind : the kind of the control parameter
Returns
the value of the control parameter
Definition at line 363 of file ControlParameters.h.
References ControlParameterValue::d, DOUBLE, ControlParameterValue::f, FLOAT, ControlParameterValue::i, S64, VEC3_DOUBLE, VEC3_FLOAT, ControlParameterValue::vec3d, and ControlParameterValue::vec3f.
{
     ControlParameterValue value;
     if (kind != _kind) {
       throw std::runtime_error("Control parameter type mismatch in get");
     }
     switch (_kind) {
       case ControlParameterValueKind::FLOAT:
         value.f = *_value.f;
         break;
       case ControlParameterValueKind::DOUBLE:
         value.d = *_value.d;
         break;
       case ControlParameterValueKind::S64:
         value.i = *_value.i;
         break;
       case ControlParameterValueKind::VEC3_FLOAT:
         value.vec3f[0] = _value.vec3f[0];
         value.vec3f[1] = _value.vec3f[1];
         value.vec3f[2] = _value.vec3f[2];
         break;
       case ControlParameterValueKind::VEC3_DOUBLE:
         value.vec3d[0] = _value.vec3d[0];
         value.vec3d[1] = _value.vec3d[1];
         value.vec3d[2] = _value.vec3d[2];
         break;
       default:
         throw std::runtime_error("Control parameter invalid kind in get");
     }
     return value;
   }
void ControlParameter::initializeDouble (double d) inline
Set initial value of the control parameter. Checks to see that the types are correct
Definition at line 255 of file ControlParameters.h.
References DOUBLE.
{
     if (_kind != ControlParameterValueKind::DOUBLE) {
       throw std::runtime_error("Tried to initialize control parameter " +
                                _name + " as a double!");
     }
     _set = true;
     *_value.d = d;
   }
void ControlParameter::initializeFloat (float f) inline
Set initial value of the control parameter. Checks to see that the types are correct
Definition at line 269 of file ControlParameters.h.
References FLOAT.
{
     if (_kind != ControlParameterValueKind::FLOAT) {
       throw std::runtime_error("Tried to initialize control parameter " +
                                _name + " as a float!");
     }
     _set = true;
     *_value.f = f;
   }
void ControlParameter::initializeInteger (s64 i) inline
Set initial value of the control parameter. Checks to see that the types are correct
Definition at line 282 of file ControlParameters.h.
References S64.
{
     if (_kind != ControlParameterValueKind::S64) {
       throw std::runtime_error("Tried to initialize control parameter " +
                                _name + " as an integer!");
     }
     _set = true;
     *_value.i = i;
   }
void ControlParameter::initializeVec3d (const Vec3< double > & v) inline
Set initial value of the control parameter. Checks to see that the types are correct
Definition at line 310 of file ControlParameters.h.
References VEC3_DOUBLE.
{
     if (_kind != ControlParameterValueKind::VEC3_DOUBLE) {
       throw std::runtime_error("Tried to initialize control parameter " +
                                _name + " as a vector3d");
     }
     _set = true;
     _value.vec3d[0] = v[0];
     _value.vec3d[1] = v[1];
     _value.vec3d[2] = v[2];
   }
void ControlParameter::initializeVec3f (const Vec3< float > & v) inline
Set initial value of the control parameter. Checks to see that the types are correct
Definition at line 295 of file ControlParameters.h.
References VEC3_FLOAT.
{
     if (_kind != ControlParameterValueKind::VEC3_FLOAT) {
       throw std::runtime_error("Tried to initialize control parameter " +
                                _name + " as a vector3f");
     }
     _set = true;
     _value.vec3f[0] = v[0];
     _value.vec3f[1] = v[1];
     _value.vec3f[2] = v[2];
   }
void ControlParameter::set (ControlParameterValue value, ControlParameterValueKind kind) inline
Set a control parameter by value. Performs type checking
Parameters
value : value to set
kind : kind of the value
Definition at line 327 of file ControlParameters.h.
References DOUBLE, FLOAT, S64, VEC3_DOUBLE, and VEC3_FLOAT.
{
     if (kind != _kind) {
       throw std::runtime_error("Control parameter type mismatch in set");
     }
     switch (kind) {
       case ControlParameterValueKind::FLOAT:
         *_value.f = value.f;
         break;
       case ControlParameterValueKind::DOUBLE:
         *_value.d = value.d;
         break;
       case ControlParameterValueKind::S64:
         *_value.i = value.i;
         break;
       case ControlParameterValueKind::VEC3_FLOAT:
         _value.vec3f[0] = value.vec3f[0];
         _value.vec3f[1] = value.vec3f[1];
         _value.vec3f[2] = value.vec3f[2];
         break;
       case ControlParameterValueKind::VEC3_DOUBLE:
         _value.vec3d[0] = value.vec3d[0];
         _value.vec3d[1] = value.vec3d[1];
         _value.vec3d[2] = value.vec3d[2];
         break;
       default:
         throw std::runtime_error("Control parameter invalid kind in set");
     }
     _set = true;
   }
bool ControlParameter::setFromString (const std::string & value) inline
Set the value of a control parameter from a string. Numbers are just numbers. Vec3's are like [1,2,3]
Parameters
value : the string representing the value
Returns
if the set was successful
Definition at line 436 of file ControlParameters.h.
References DOUBLE, FLOAT, S64, VEC3_DOUBLE, and VEC3_FLOAT.
{
     switch (_kind) {
       case ControlParameterValueKind::DOUBLE:
         *_value.d = std::stod(value);
         break;
       case ControlParameterValueKind::FLOAT:
         *_value.f = std::stof(value);
         break;
       case ControlParameterValueKind::S64:
         *_value.i = std::stoll(value);
         break;
       case ControlParameterValueKind::VEC3_FLOAT: {
         Vec3<float> v = stringToVec3<float>(value);
         _value.vec3f[0] = v[0];
         _value.vec3f[1] = v[1];
         _value.vec3f[2] = v[2];
       } break;
       case ControlParameterValueKind::VEC3_DOUBLE: {
         Vec3<double> v = stringToVec3<double>(value);
         _value.vec3d[0] = v[0];
         _value.vec3d[1] = v[1];
         _value.vec3d[2] = v[2];
       } break;
       default:
         return false;
     }
     return true;
   }
std::string ControlParameter::toString () inline
Convert the value to a string that works in a YAML file
Definition at line 397 of file ControlParameters.h.
References DOUBLE, FLOAT, numberToString(), S64, VEC3_DOUBLE, and VEC3_FLOAT.
{
     std::string result;
     switch (_kind) {
       case ControlParameterValueKind::DOUBLE:
         result += numberToString(*_value.d);
         break;
       case ControlParameterValueKind::FLOAT:
         result += numberToString(*_value.f);
         break;
       case ControlParameterValueKind::S64:
         result += std::to_string(*_value.i);
         break;
       case ControlParameterValueKind::VEC3_FLOAT:
         result += "[";
         result += numberToString(_value.vec3f[0]) + ", ";
         result += numberToString(_value.vec3f[1]) + ", ";
         result += numberToString(_value.vec3f[2]) + "]";
         break;
       case ControlParameterValueKind::VEC3_DOUBLE:
         result += "[";
         result += numberToString(_value.vec3d[0]) + ", ";
         result += numberToString(_value.vec3d[1]) + ", ";
         result += numberToString(_value.vec3d[2]) + "]";
         break;
       default:
         result += "<unknown type " + std::to_string((u32)(_kind)) +
                   "> (add it yourself in ControlParameters.h!)";
         break;
     }
     return result;
   }
void ControlParameter::truncateName () inline
Make sure that the control parameter name is short enough to fit in the control parameter request message.
Definition at line 243 of file ControlParameters.h.
References CONTROL_PARAMETER_MAXIMUM_NAME_LENGTH.
                       {
     if (_name.length() > CONTROL_PARAMETER_MAXIMUM_NAME_LENGTH) {
       printf("[Error] control parameter name %s is too long, shortening to ", _name.c_str());
       _name.resize(CONTROL_PARAMETER_MAXIMUM_NAME_LENGTH - 1);
       printf("%s\n", _name.c_str());
     }
   }
Member Data Documentation
ControlParameterValueKind ControlParameter::_kind
Definition at line 469 of file ControlParameters.h.
std::string ControlParameter::_name
Definition at line 467 of file ControlParameters.h.
bool ControlParameter::_set = false
Definition at line 465 of file ControlParameters.h.
ControlParameterValue ControlParameter::_staticValue
Definition at line 470 of file ControlParameters.h.
std::string ControlParameter::_units
Definition at line 468 of file ControlParameters.h.
ControlParameterValuePtr ControlParameter::_value
Definition at line 466 of file ControlParameters.h.
The documentation for this class was generated from the following file:
ControlParameters.h