Cheetah Software: DynamicsSimulator< T > Class Template Reference
DynamicsSimulator< T > Class Template Reference
#include <DynamicsSimulator.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW DynamicsSimulator (FloatingBaseModel< T > &model, bool useSpringDamper=false)
void step (T dt, const DVec< T > &tau, T kp, T kd)
Initialize simulator with given model.
void runABA (const DVec< T > &tau)
Simulate forward one step.
void forwardKinematics ()
Do forward kinematics for feet.
void integrate (T dt)
Integrate to find new _state.
void setState (const FBModelState< T > &state)
void setHoming (const RobotHomingInfo< T > &homing)
const FBModelState< T > & getState () const
const FBModelStateDerivative< T > & getDState () const
void setAllExternalForces (const vectorAligned< SVec< T >> &forces)
void addCollisionPlane (T mu, T rest, T height)
void addCollisionBox (T mu, T rest, T depth, T width, T height, const Vec3< T > &pos, const Mat3< T > &ori)
void addCollisionMesh (T mu, T rest, T grid_size, const Vec3< T > &left_corner_loc, const DMat< T > &height_map)
size_t getNumBodies ()
const size_t & getTotalNumGC ()
const Vec3< T > & getContactForce (size_t idx)
const FloatingBaseModel< T > & getModel ()
Private Member Functions
void updateCollisions (T dt, T kp, T kd)
Private Attributes
FBModelState< T > _state
Update ground collision list.
FBModelStateDerivative< T > _dstate
FloatingBaseModel< T > & _model
vector< CollisionPlane< T > > _collisionPlanes
ContactConstraint< T > * _contact_constr
SVec< T > _lastBodyVelocity
bool _useSpringDamper
RobotHomingInfo< T > _homing
Detailed Description
template<typename T>
class DynamicsSimulator< T >
Class (containing state) for dynamics simulation of a floating-base system
Definition at line 42 of file DynamicsSimulator.h.
Constructor & Destructor Documentation
template<typename T> DynamicsSimulator< T >::DynamicsSimulator (FloatingBaseModel< T > & model, bool useSpringDamper = false)
Initialize the dynamics simulator by allocating memory for ABA matrices
Definition at line 17 of file DynamicsSimulator.cpp.
References DynamicsSimulator< T >::_contact_constr, DynamicsSimulator< T >::_dstate, DynamicsSimulator< T >::_lastBodyVelocity, DynamicsSimulator< T >::_model, DynamicsSimulator< T >::_state, and DynamicsSimulator< T >::_useSpringDamper.
     : _model(model), _useSpringDamper(useSpringDamper) {
   if (_useSpringDamper) {
     _contact_constr = new ContactSpringDamper<T>(&_model);
   } else {
     _contact_constr = new ContactImpulse<T>(&_model);
   }
   _state.bodyVelocity = SVec<T>::Zero();
   _state.bodyPosition = Vec3<T>::Zero();
   _state.bodyOrientation = Quat<T>::Zero();
   _state.q = DVec<T>::Zero(_model._nDof - 6);
   _state.qd = DVec<T>::Zero(_model._nDof - 6);
   _dstate.qdd = DVec<T>::Zero(_model._nDof - 6);
   _lastBodyVelocity.setZero();
 }
Member Function Documentation
template<typename T> void DynamicsSimulator< T >::addCollisionBox (T mu, T rest, T depth, T width, T height, const Vec3< T > & pos, const Mat3< T > & ori) inline
Add a box
Parameters
mu : friction coefficient
rest : restitution coefficient
depth : depth of box
width : width of box
height : height of box
pos : position of center of box
ori : orientation of box (rotation matrix)
Definition at line 117 of file DynamicsSimulator.h.
{
     _contact_constr->AddCollision(
         new CollisionBox<T>(mu, rest, depth, width, height, pos, ori));
   }
template<typename T> void DynamicsSimulator< T >::addCollisionMesh (T mu, T rest, T grid_size, const Vec3< T > & left_corner_loc, const DMat< T > & height_map) inline
Add a height map mesh
Parameters
mu : friction coefficient
rest : restitution coefficient
grid_size : size of each grid (must be square)
left_corner_loc : location of 0,0 coordinate
height_map : height map data
Definition at line 131 of file DynamicsSimulator.h.
{
     _contact_constr->AddCollision(
         new CollisionMesh<T>(mu, rest, grid_size, left_corner_loc, height_map));
   }
template<typename T> void DynamicsSimulator< T >::addCollisionPlane (T mu, T rest, T height) inline
Add a collision plane (xy plane)
Parameters
mu : friction coefficient
rest : restitution coefficient
height : height of plane
Definition at line 103 of file DynamicsSimulator.h.
{
     _contact_constr->AddCollision(new CollisionPlane<T>(mu, rest, height));
   }
template<typename T> void DynamicsSimulator< T >::forwardKinematics () inline
Do forward kinematics for feet.
Definition at line 55 of file DynamicsSimulator.h.
 { _model.forwardKinematics(); }
template<typename T> const Vec3<T>& DynamicsSimulator< T >::getContactForce (size_t idx) inline
Get the force at a given contact point
Parameters
idx : The index of the contact point
Returns
The force at the contact point (global frame)
Definition at line 155 of file DynamicsSimulator.h.
{
     return _contact_constr->getGCForce(idx);
   }
template<typename T> const FBModelStateDerivative<T>& DynamicsSimulator< T >::getDState () const inline
Get the most recently calculated state derivative (updated by runABA)
Returns
Definition at line 86 of file DynamicsSimulator.h.
 { return _dstate; }
template<typename T> const FloatingBaseModel<T>& DynamicsSimulator< T >::getModel () inline
Get the floating base model which is being simulated
Returns
floating base model
Definition at line 163 of file DynamicsSimulator.h.
 { return _model; }
template<typename T> size_t DynamicsSimulator< T >::getNumBodies () inline
Get the number of bodies (not including rotors)
Returns
number of bodies
Definition at line 142 of file DynamicsSimulator.h.
 { return _model._nDof; }
template<typename T> const FBModelState<T>& DynamicsSimulator< T >::getState () const inline
Get the state of the robot
Returns
Definition at line 80 of file DynamicsSimulator.h.
 { return _state; }
template<typename T> const size_t& DynamicsSimulator< T >::getTotalNumGC () inline
Get the number of maximum possible ground contact points
Returns
The number of maximum possible ground contact points
Definition at line 148 of file DynamicsSimulator.h.
 { return _model._nGroundContact; }
template<typename T> void DynamicsSimulator< T >::integrate (T dt)
Integrate to find new _state.
Integrate the floating base state
Parameters
dt timestep
Definition at line 93 of file DynamicsSimulator.cpp.
References DynamicsSimulator< T >::_contact_constr, DynamicsSimulator< T >::_dstate, DynamicsSimulator< T >::_lastBodyVelocity, DynamicsSimulator< T >::_state, DynamicsSimulator< T >::_useSpringDamper, spatial::createSXform(), ori::integrateQuat(), ori::integrateQuatImplicit(), ori::quaternionToRotationMatrix(), spatial::rotationFromSXform(), and ori::X.
{
   if (_useSpringDamper) {
     Vec3<T> omegaBody = _state.bodyVelocity.template block<3, 1>(0, 0);
     Mat6<T> X = createSXform(quaternionToRotationMatrix(_state.bodyOrientation),
                              _state.bodyPosition);
     RotMat<T> R = rotationFromSXform(X);
     Vec3<T> omega0 = R.transpose() * omegaBody;
     // actual integration
     _state.qd += _dstate.qdd * dt;
     _state.q += _state.qd * dt;
     _state.bodyVelocity += _dstate.dBodyVelocity * dt;
     _state.bodyPosition += _dstate.dBodyPosition * dt;
     _state.bodyOrientation = integrateQuat(_state.bodyOrientation, omega0, dt);
   } else {
     // actual integration
     // Velocity Update by integrating acceleration
     _state.qd += _dstate.qdd * dt;
     _state.bodyVelocity += _dstate.dBodyVelocity * dt;
     // Contact Constraint Velocity Updated
     _contact_constr->UpdateQdot(_state);
     // Prepare body velocity integration
     RotMat<T> R_body = quaternionToRotationMatrix(_state.bodyOrientation);
     _dstate.dBodyPosition =
         R_body.transpose() * _state.bodyVelocity.template block<3, 1>(3, 0);
     Vec3<T> omegaBody = _state.bodyVelocity.template block<3, 1>(0, 0);
     // Position Update
     _state.q += _state.qd * dt;
     _state.bodyPosition += _dstate.dBodyPosition * dt;
     _state.bodyOrientation =
         integrateQuatImplicit(_state.bodyOrientation, omegaBody, dt);
     _dstate.dBodyVelocity = (_state.bodyVelocity - _lastBodyVelocity) / dt;
     _lastBodyVelocity = _state.bodyVelocity;
   }
 }
template<typename T> void DynamicsSimulator< T >::runABA (const DVec< T > & tau) inline
Simulate forward one step.
Find _dstate with the articulated body algorithm
Definition at line 52 of file DynamicsSimulator.h.
 { _model.runABA(tau, _dstate); }
template<typename T> void DynamicsSimulator< T >::setAllExternalForces (const vectorAligned< SVec< T >> & forces) inline
Add external forces. These are added on top of the ground reaction forces The i-th force is the spatial force applied to body i. This is cleared after each step of the simulator.
Definition at line 93 of file DynamicsSimulator.h.
{
     _model._externalForces = forces;
   }
template<typename T> void DynamicsSimulator< T >::setHoming (const RobotHomingInfo< T > & homing) inline
Set the homing parameters of the simulator
Parameters
homing : homing parameters
Definition at line 72 of file DynamicsSimulator.h.
{
     _homing = homing;
   }
template<typename T> void DynamicsSimulator< T >::setState (const FBModelState< T > & state) inline
Set the state of the robot being simulated
Definition at line 63 of file DynamicsSimulator.h.
{
     _state = state;
     _model.setState(state);  // force recalculate dynamics
   }
template<typename T> void DynamicsSimulator< T >::step (T dt, const DVec< T > & tau, T kp, T kd)
Initialize simulator with given model.
Take one simulation step
Parameters
dt : timestep duration
tau : joint torques
Definition at line 41 of file DynamicsSimulator.cpp.
References DynamicsSimulator< T >::_homing, DynamicsSimulator< T >::_model, DynamicsSimulator< T >::_state, spatial::forceToSpatialForce(), DynamicsSimulator< T >::forwardKinematics(), DynamicsSimulator< T >::integrate(), ori::quatToso3(), ori::rotationMatrixToQuaternion(), ori::rpyToRotMat(), DynamicsSimulator< T >::runABA(), and DynamicsSimulator< T >::updateCollisions().
{
   // fwd-kin on gc points
   // compute ground contact forces
   // aba
   // integrate
   forwardKinematics();           // compute forward kinematics
   updateCollisions(dt, kp, kd);  // process collisions
   // Process Homing
   if( _homing.active_flag) {
     Mat3<T> R10_des = rpyToRotMat(_homing.rpy);              // R10_des
     Mat3<T> R10_act = _model.getOrientation(5).transpose();  // R10
     Mat3<T> eR01 = R10_des.transpose()*R10_act;              // eR * R01 = R01_des
     Vec4<T> equat = rotationMatrixToQuaternion(eR01.transpose());
     Vec3<T> angle_axis = quatToso3(equat); // in world frame
     Vec3<T> p = _model.getPosition(5);
     Vec3<T> f = _homing.kp_lin*(_homing.position - p)-_homing.kd_lin*_model.getLinearVelocity(5);
     // Note: External forces are spatial forces in the {0} frame.
     _model._externalForces.at(5) += forceToSpatialForce(f,p);
     _model._externalForces.at(5).head(3) += _homing.kp_ang*angle_axis - _homing.kd_ang*_model.getAngularVelocity(5);
   }
   runABA(tau);                   // dynamics algorithm
   integrate(dt);                 // step forward
   _model.setState(_state);
   _model.resetExternalForces();  // clear external forces
   _model.resetCalculationFlags();
 }
template<typename T> void DynamicsSimulator< T >::updateCollisions (T dt, T kp, T kd) private
Run spring-damper collisions
Parameters
dt : timestep
kp : spring constant
kd : damping constant
Definition at line 83 of file DynamicsSimulator.cpp.
References DynamicsSimulator< T >::_contact_constr, and DynamicsSimulator< T >::_model.
{
   _model.forwardKinematics();
   _contact_constr->UpdateExternalForces(kp, kd, dt);
 }
Member Data Documentation
template<typename T> vector<CollisionPlane<T> > DynamicsSimulator< T >::_collisionPlanes private
Definition at line 170 of file DynamicsSimulator.h.
template<typename T> ContactConstraint<T>* DynamicsSimulator< T >::_contact_constr private
Definition at line 171 of file DynamicsSimulator.h.
template<typename T> FBModelStateDerivative<T> DynamicsSimulator< T >::_dstate private
Definition at line 168 of file DynamicsSimulator.h.
template<typename T> RobotHomingInfo<T> DynamicsSimulator< T >::_homing private
Definition at line 175 of file DynamicsSimulator.h.
template<typename T> SVec<T> DynamicsSimulator< T >::_lastBodyVelocity private
Definition at line 172 of file DynamicsSimulator.h.
template<typename T> FloatingBaseModel<T>& DynamicsSimulator< T >::_model private
Definition at line 169 of file DynamicsSimulator.h.
template<typename T> FBModelState<T> DynamicsSimulator< T >::_state private
Update ground collision list.
Definition at line 167 of file DynamicsSimulator.h.
template<typename T> bool DynamicsSimulator< T >::_useSpringDamper private
Definition at line 173 of file DynamicsSimulator.h.
The documentation for this class was generated from the following files:
DynamicsSimulator.h
DynamicsSimulator.cpp