Cheetah Software: rt_ethercat.h File Reference
rt_ethercat.h File Reference
#include <cstdint>
Functions
void rt_ethercat_init ()
void rt_ethercat_run ()
Send and receive data over EtherCAT.
void rt_ethercat_get_data (TiBoardData *data)
void rt_ethercat_set_command (TiBoardCommand *command)
Function Documentation
void rt_ethercat_get_data (TiBoardData * data)
Definition at line 311 of file rt_ethercat.cpp.
References data_mutex.
{
   data_mutex.lock();
   for(int slave = 0; slave < 4; slave++) {
     TiBoardData* slave_src = (TiBoardData*)(ec_slave[slave + 1].inputs);
     if(slave_src)
       data[slave] = *(TiBoardData*)(ec_slave[slave + 1].inputs);
   }
   data_mutex.unlock();
 }
void rt_ethercat_init ()
Definition at line 241 of file rt_ethercat.cpp.
References ADAPTER_NAME, ecatcheck(), run_ethercat(), and thread1.
 {
   printf("[EtherCAT] Initializing EtherCAT\n");
   //initialize monitoring thread
   osal_thread_create((void*)&thread1, 128000, (void*)&ecatcheck, (void*) &ctime);
   //try initialization until it succeeds
   int i;
   int rc;
   for(i = 1; i < 100; i++)
   {
     printf("[EtherCAT] Attempting to start EtherCAT, try %d of 100.\n", i);
     rc = run_ethercat(ADAPTER_NAME); // todo?
     if(rc) break;
     osal_usleep(1000000);
   }
   if(rc) printf("[EtherCAT] EtherCAT successfully initialized on attempt %d \n", i);
   else
   {
     printf("[EtherCAT Error] Failed to initialize EtherCAT after 100 tries. \n");
   }
 }
void rt_ethercat_run ()
Send and receive data over EtherCAT.
In Simulation, send data over LCM On the robt, verify the EtherCAT connection is still healthy, send data, receive data, and check for lost packets
Definition at line 277 of file rt_ethercat.cpp.
References command_mutex, data_mutex, degraded_handler(), expectedWKC, K_ETHERCAT_ERR_MAX, K_ETHERCAT_ERR_PERIOD, wkc, wkc_err_count, and wkc_err_iteration_count.
 {
   //check connection
   if(wkc_err_iteration_count > K_ETHERCAT_ERR_PERIOD)
   {
     wkc_err_count = 0;
     wkc_err_iteration_count = 0;
   }
   if(wkc_err_count > K_ETHERCAT_ERR_MAX)
   {
     printf("[EtherCAT Error] Error count too high!\n");
     //program terminates in degraded handler.
     degraded_handler();
   }
   //send
   command_mutex.lock();
   ec_send_processdata();
   command_mutex.unlock();
   //receive
   data_mutex.lock();
   wkc = ec_receive_processdata(EC_TIMEOUTRET);
   data_mutex.unlock();
   //check for dropped packet
   if(wkc < expectedWKC)
   {
     printf("\x1b[31m[EtherCAT Error] Dropped packet (Bad WKC!)\x1b[0m\n");
     wkc_err_count++;
   }
   wkc_err_iteration_count++;
 }
void rt_ethercat_set_command (TiBoardCommand * command)
Definition at line 321 of file rt_ethercat.cpp.
References command_mutex.
{
   command_mutex.lock();
   for(int slave = 0; slave < 4; slave++) {
     TiBoardCommand* slave_dest = (TiBoardCommand*)(ec_slave[slave + 1].outputs);
     if(slave_dest)
       *(TiBoardCommand*)(ec_slave[slave + 1].outputs) = command[slave];
   }
   command_mutex.unlock();
 }